export const ALL_ROLES = [
  'ops-lead',
  'product-lead',
  'dev-lead',
  'design-lead',
  'business-lead',
  'tpm',
  'pm',
  'apm',
  'developer',
  'designer',
  'business',
  'pm-advisor',
  'dev-advisor',
  'design-advisor',
  'business-advisor'
];
export const LEAD_ROLES = ['ops-lead', 'product-lead', 'dev-lead', 'design-lead', 'business-lead'];
export const ADVISOR_ROLES = ['pm-advisor', 'dev-advisor', 'design-advisor', 'business-advisor'];
export const ALL_COLLEGES = [
  'eng',
  'cas',
  'cals',
  'dyson',
  'humec',
  'hotel',
  'ilr',
  'brooks',
  'aap'
];

export const ALL_MAJORS = [
  'Africana Studies',
  'Agricultural Sciences',
  'American Studies',
  'Animal Science',
  'Anthropology',
  'Applied Economics and Management',
  'Archaeology',
  'Architecture',
  'Asian Studies',
  'Astronomy',
  'Atmospheric Science',
  'Biological Engineering',
  'Biological Sciences',
  'Biology and Society',
  'Biomedical Engineering',
  'Biometry and Statistics',
  'Chemical Engineering',
  'Chemistry',
  'China and Asia-Pacific Studies',
  'Civil Engineering',
  'Classics',
  'Cognitive Science',
  'College Scholar',
  'Communication',
  'Comparative Literature',
  'Computer Science',
  'Design and Environmental Analysis',
  'Earth and Atmospheric Sciences',
  'Economics',
  'Electrical and Computer Engineering',
  'Engineering Physics',
  'English',
  'Entomology',
  'Environment and Sustainability',
  'Environmental Engineering',
  'Fashion Design and Management',
  'Feminist, Gender, and Sexuality Studies',
  'Fiber Science',
  'Fine Arts',
  'Food Science',
  'French',
  'German Studies',
  'Global and Public Health Sciences',
  'Global Development',
  'Government',
  'Health Care Policy',
  'History',
  'History of Art',
  'Hotel Administration',
  'Human Biology, Health, and Society',
  'Human Development',
  'Independent Major',
  'Industrial and Labor Relations (ILR)',
  'Information Science',
  'Information Science, Systems, and Technology',
  'Italian',
  'Jewish Studies',
  'Landscape Architecture',
  'Linguistics',
  'Materials Science and Engineering',
  'Mathematics',
  'Mechanical Engineering',
  'Music',
  'Near Eastern Studies',
  'Nutritional Sciences',
  'Operations Research and Engineering',
  'Performing and Media Arts',
  'Philosophy',
  'Physics',
  'Plant Sciences',
  'Psychology',
  'Public Policy',
  'Religious Studies',
  'Science and Technology Studies',
  'Sociology',
  'Spanish',
  'Statistical Science',
  'Undecided',
  'Urban and Regional Studies',
  'Viticulture and Enology'
];

export const ALL_MINORS = [
  'Actuarial Science',
  'Aerospace Engineering',
  'Africana Studies',
  'American Indian and Indigenous Studies',
  'American Sign Language | Deaf Studies',
  'American Studies',
  'Animal Science',
  'Anthropology',
  'Applied Economics',
  'Applied Exercise Science',
  'Applied Mathematics',
  'Arabic',
  'Archaeology',
  'Architecture',
  'Artificial Intelligence',
  'Asian American Studies',
  'Astrobiology',
  'Astronomy',
  'Atmospheric Science',
  'Biological Engineering',
  'Biomedical Engineering',
  'Biomedical Sciences',
  'Biometry and Statistics',
  'Business',
  'Caribbean Studies',
  'China and Asia-Pacific Studies',
  'Civil Infrastructure',
  'Classical Civilization',
  'Classics',
  'Climate Change',
  'Cognitive Science',
  'Communication',
  'Community Food Systems',
  'Comparative Literature',
  'Computer Science',
  'Creative Writing',
  'Crime, Prisons, Education, and Justice',
  'Crop Management',
  'Dance',
  'Data Science',
  'Data Science in Astronomy',
  'Demography',
  'Design and Environmental Analysis',
  'Digital Agriculture',
  'Dyson Business Minor for Engineers',
  'Dyson Business Minor for Life Sciences',
  'Earth and Atmospheric Sciences',
  'East Asian Studies',
  'Education',
  'Electrical and Computer Engineering',
  'Engineering Communications',
  'Engineering Management',
  'English',
  'Entomology',
  'Entrepreneurship',
  'Environment and Sustainability',
  'Environmental Engineering',
  'European Studies',
  'Fashion Studies',
  'Feminist, Gender, and Sexuality Studies',
  'Fiber Science',
  'Film',
  'Fine Arts',
  'Food and Agricultural Business',
  'Food Science',
  'French',
  'Fungal Biology',
  'Game Design',
  'German Studies',
  'Gerontology',
  'Global Asia Studies',
  'Global Development',
  'Global Health',
  'Health Policy',
  'Healthy Futures',
  'History',
  'History of Art',
  'History of Capitalism',
  'Horticulture',
  'Human Development',
  'Inequality Studies',
  'Infectious Disease Biology',
  'Information Science',
  'International Markets and Development',
  'International Relations',
  'Italian',
  'Jewish Studies',
  'Landscape Architecture',
  'Latin American Studies',
  'Latina/o Studies',
  'Law and Society',
  'Leadership',
  'Lesbian, Gay, Bisexual, and Transgender Studies',
  'Linguistics',
  'Marine Biology',
  'Materials Science and Engineering',
  'Mathematics',
  'Mechanical Engineering',
  'Media Studies',
  'Medieval Studies',
  'Microbial Sciences',
  'Migration Studies',
  'Minority, Indigenous, and Third World Studies',
  'Moral Psychology',
  'Music',
  'Near Eastern Studies',
  'Nutrition and Health',
  'Operations Research & Management Science',
  'Performing and Media Arts',
  'Philosophy',
  'Physics',
  'Plant Breeding',
  'Plant Sciences',
  'Policy Analysis and Management',
  'Portuguese and Brazilian Studies',
  'Psychology',
  'Public History',
  'Public Policy',
  'Public Service Studies',
  'Real Estate',
  'Religious Studies',
  'Robotics',
  'Russian',
  'Sanskrit Studies',
  'Science and Technology Studies',
  'Science Communication and Public Engagement',
  'Smart Cities',
  'Soil Science',
  'South Asian Studies',
  'Southeast Asian Studies',
  'Spanish',
  'Sustainable Agricultural and Food Systems',
  'Sustainable Business and Economic Policy',
  'Sustainable Energy Systems',
  'Theatre',
  'Urban and Regional Studies',
  'Viking Studies',
  'Visual Studies',
  'Viticulture & Enology'
];

export const ALUM_DTI_ROLES = ['Dev', 'Product', 'Business', 'Design'];

export const ALUM_JOB_CATEGORY = [
  'Technology',
  'Product Management',
  'Business',
  'Product Design',
  'Entrepreneurship',
  'Grad Student',
  'Other'
];
