export const MOBILE_BREAKPOINT = 640;
export const TABLET_BREAKPOINT = 768;
export const LAPTOP_BREAKPOINT = 1024;
export const LARGE_LAPTOP_BREAKPOINT = 1280;
export const MONITOR_BREAKPOINT = 1536;
