name: Build
on:
  push:
    branches:
  pull_request:
    branches: [main, staging]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: .node-version
      - name: Use Yarn Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: yarn-
      - name: Install
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Type Check
        run: yarn type-check
      - name: Format
        run: yarn format:check
      - name: Set env var if base is main
        run: |
          echo "USE_PROD_DB=true" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_IS_STAGING=false" >> $GITHUB_ENV
        if: startsWith(github.base_ref, 'main')

      - name: Set env var if base is staging
        run: |
          echo "USE_PROD_DB=false" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_IS_STAGING=true" >> $GITHUB_ENV
        if: startsWith(github.base_ref, 'staging')
      - name: see what base_ref is
        run: echo ${{ github.base_ref }}
      - name: see what env vars are set to
        run: |
          echo ${{ env.USE_PROD_DB }}
          echo ${{ env.NEXT_PUBLIC_IS_STAGING }}
      - name: Test
        env:
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
          USE_PROD_DB: ${{ echo ${{ env.USE_PROD_DB }} }}
          NEXT_PUBLIC_IS_STAGING: ${{ ${{ env.NEXT_PUBLIC_IS_STAGING }} }}

        run: yarn test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: .node-version
      - name: Use Yarn Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: yarn-
      - name: Install
        run: yarn
      - name: Build
        run: yarn workspaces run build
