name: IDOL Notifications
on:
  schedule:
    # Runs at 8AM UTC (6PM or 7PM ET) everyday. This should be an hour before pull-from-idol
    - cron: '0 23 * * MON'
    # Runs at 2PM UTC (9AM or 10AM ET) on 1/20 and 8/20 (before each semester starts)
    - cron: '0 14 20 1,8 *'

jobs:
  profile-update-notifications:
    if: contains(github.event.schedule, '0 23 * * MON')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version-file: .node-version
      - name: Use Yarn Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: yarn-
      - name: Install
        run: yarn
      - name: Profile update notifications
        env:
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
          OAUTH_CLIENTID: ${{ secrets.OAUTH_CLIENTID}}
          OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
          OAUTH_REFRESH_TOKEN: ${{ secrets.OAUTH_REFRESH_TOKEN }}
        run: yarn workspace backend send-profile-update-notifications

  tec-request-notification:
    if: contains(github.event.schedule, '0 23 * * MON')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version-file: .node-version
      - name: Use Yarn Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: yarn-
      - name: Install
        run: yarn
      - name: TEC request notification
        env:
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
          OAUTH_CLIENTID: ${{ secrets.OAUTH_CLIENTID}}
          OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
          OAUTH_REFRESH_TOKEN: ${{ secrets.OAUTH_REFRESH_TOKEN }}
        run: yarn workspace backend send-tec-notifications

  member-archive-reminder:
    if: contains(github.event.schedule, '0 14 20 1,8 *')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Use Yarn Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/yarn
          key: yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: yarn-
      - name: Install
        run: yarn
      - name: Member archive reminder
        env:
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
          OAUTH_CLIENTID: ${{ secrets.OAUTH_CLIENTID}}
          OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
          OAUTH_REFRESH_TOKEN: ${{ secrets.OAUTH_REFRESH_TOKEN }}
        run: yarn workspace backend send-member-archive-reminder