name: Profile Update Notification
on:
  schedule:
    # Runs script at 10PM UTC (5PM or 6PM ET) every day. This should be two hours before pull-from-idol
    - cron: '0 23 * * *'

jobs:
  profile-update-notification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Use Yarn Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/yarn
          key: yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: yarn-
      - name: Install
        run: yarn
      - name: Profile update notifications
        env:
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
          OAUTH_CLIENTID: ${{ secrets.OAUTH_CLIENTID}}
          OAUTH_CLIENT_SECRET: ${{ secrets.OAUTH_CLIENT_SECRET }}
          OAUTH_REFRESH_TOKEN: ${{ secrets.OAUTH_REFRESH_TOKEN }}
        run: yarn workspace backend send-profile-update-notifications
