name: Rebuild DTI from Master Every 2 Hours
on:
  schedule:
  - cron: '0 */2 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger the build webhook on Netlify
      run: curl -s -X POST "https://api.netlify.com/build_hooks/${TOKEN}"
      env:
        TOKEN: ${{ secrets.NETLIFY_CRON_BUILD_HOOK }}