name: Restore Back Up to Prod Database
on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version-file: .node-version
      - name: Use Yarn Cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: yarn-
      - name: Install
        run: yarn
      - name: Restore Back Up to Prod Database
        env:
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_BACKUP_PRIVATE_KEY: ${{ secrets.FIREBASE_BACKUP_PRIVATE_KEY }}
          FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
          FIREBASE_BACKUP_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_BACKUP_PRIVATE_KEY_ID }}
        run: yarn workspace backend restore-from-backup
